[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
skip_glob = ".python_packages"

[tool.black]
exclude = '''
/(
    \.git          # root of the project
  | \.hg
  | \.mypy_cache
  | \.python_packages
  | \.pytest_cache
)/
'''