service: ${env:NAME_PREFIX,''}{{ cookiecutter.name|slugify }}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  region: ${env:AWS_REGION,'eu-central-1'}
  httpApi:
    cors: true
  logs:
    httpApi: true
  environment:
    AWS_REGION: eu-central-1
    COMPONENT_NAME: {{ cookiecutter.name|slugify }}
    LOCALSTACK_URL: http://localhost:4566
    {% if cookiecutter.use_commercetools|int -%}
    CT_API_URL: https://api.europe-west1.gcp.commercetools.com
    CT_AUTH_URL: https://auth.europe-west1.gcp.commercetools.com
    CT_PROJECT_KEY: ${file(./.credentials.json):CT_PROJECT_KEY}
    CT_CLIENT_ID: ${file(./.credentials.json):CT_CLIENT_ID}
    CT_CLIENT_SECRET: ${file(./.credentials.json):CT_CLIENT_SECRET}
    CT_SCOPES: ${file(./.credentials.json):CT_SCOPES}
    {%- endif %}

custom:
  serverless-offline:
    noPrependStageInUrl: true
  webpack:
    webpackConfig: 'webpack.config.ts'
    packager: 'yarn'
    includeModules: true

functions:
  service:
    handler: src/rest/handler.handler
    events:
      - httpApi:
          method: '*'
          path: '/{proxy+}'
