service: {{ cookiecutter.name|slugify }}
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  region: ${env:AWS_REGION,'eu-central-1'}
  httpApi:
    cors: true
  logs:
    httpApi: true
  environment:
    AWS_REGION: eu-central-1
    COMPONENT_NAME: {{ cookiecutter.name|slugify }}
    LOCALSTACK_URL: http://localhost:4566
    {% if cookiecutter.use_commercetools|int -%}
    CT_API_URL: https://api.europe-west1.gcp.commercetools.com
    CT_AUTH_URL: https://auth.europe-west1.gcp.commercetools.com{% endif %}

custom:
  serverless-offline:
    noPrependStageInUrl: true
  esbuild:
    bundle: true
    minify: true
    target: node12
    platform: node
    sourcemap: true

functions:
  service:
    handler: src/http/index.handler
    events:
      - httpApi:
          method: '*'
          path: '/{proxy+}'
